In [109]:
def hello():
    """This function says hello and greet you"""
    print("Hello!")
    print("Glad to meet you")
hello()

Hello!
Glad to meet you


In [111]:
#Function defination
def find_square(num):
    result = num * num
    return result
#Function call
square = find_square(3)
print("Square :", square)

Square : 9


In [113]:
#Lambda function
x = lambda a : a + 10
print(x(5))

15


In [115]:
def calculate_carbon_footprint(energy_consumption, emission_factor):
    """
    This function calculates the carbon footprint based on energy consumption
    (in kilowatt-hours) and the emission factor (in kg C02 per kWh).
    """
    return energy_consumption * emission_factor

In [117]:
#ExampLe usage:
energy_consumption = 1000
emission_factor = 0.475
# in kWh
# kg CO2 per kwh
carbon_footprint = calculate_carbon_footprint (energy_consumption, emission_factor)
print (f"Carbon Footprint: {carbon_footprint} kg CO2")
#This will calculate and print the carbon footprint for the given energy consumption and emission factor.

Carbon Footprint: 475.0 kg CO2


In [119]:
#List of cities with their carbon footprints in tons CO2 per month
cities = [
    {"name":"City A","carbon_footprint":500},
    {"name":"City B","carbon_footprint":350},
    {"name":"City C","carbon_footprint":600},
    {"name":"City D","carbon_footprint":200},
]

#Lambda function to filter cities below the threshold (400 ton CO2)
sustainability_threshold = 400
sustainable_cities = list(filter(lambda city: city["carbon_footprint"] < sustainability_threshold, cities))

#Printing the filtered list of suitanable cities
print("Sustainable Cities:")
for city in sustainable_cities:
    print(city["name"])

Sustainable Cities:
City B
City D


In [121]:
import pandas as pd
# SampLe renewable energy sources data
renewable_sources = ["Solan", "Wind", "Hydropower", "Geothermal", "Biomass"]
# Sample green technology project data (for DataFrame)
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof I", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solan", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100], # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250], # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [123]:
#Create a pandas series for renewable energy source 
renewable_series = pd.Series(renewable_sources)
#Print the series 
print("Renewable energy sources")
print(renewable_series)

Renewable energy sources
0         Solan
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [125]:
#Create a Dataframe for green technology projects 
projects_df = pd.DataFrame(data)
#Print the dataframe 
print("\nGreen Technology Projects Dataframe:")
print(projects_df)


Green Technology Projects Dataframe:
              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof I       Solan             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023  


In [127]:
projects_df.head()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof I       Solan             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [129]:
projects_df.tail()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof I       Solan             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [131]:
#Acess the 'Project' column
print("\nList of Projects.")
print(projects_df["Project"])


List of Projects.
0          Solar Farm A
1        Wind Turbine X
2          Hydropower Y
3          Solar Roof I
4    Geothermal Plant P
Name: Project, dtype: object


In [133]:
print("\nList of Technology and Location.")
print(projects_df[["Technology", "Location"]])


List of Technology and Location.
   Technology    Location
0       Solar  California
1        Wind       Texas
2  Hydropower  Washington
3       Solan      Nevada
4  Geothermal       Idaho


In [135]:
#Filter projects with capacity graeter than 100%
high_capacity_projects = projects_df[projects_df["Capacity (MW)"] > 100 ]
print("\nProjects with capacity greater that 100 MW")
print(high_capacity_projects)


Projects with capacity greater that 100 MW
          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [150]:
#Add new column for cost pr MW
projects_df["Cost per MW"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]

print("\nDataFrame with Cost per MW:")
print(projects_df)


DataFrame with Cost per MW:
              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof I       Solan             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000  


In [184]:
#Aggregate the total capacity and cost
total_capacity = projects_df["Capacity (MW)"].sum()
total_cost = projects_df["Cost (Million $)"].sum()

print(f"\nTotal capacity of all projects: {total_capacity}MW")
print(f"Total cost of all projects: {total_cost} million")


Total capacity of all projects: 800MW
Total cost of all projects: 1300 million


In [188]:
#Group by 'Technology' and calculate total capacity for each type 
grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()
print("\nTotal capacity by Technology.")
print(grouped_data)


Total capacity by Technology.
Technology
Geothermal    100
Hydropower    200
Solan          50
Solar         150
Wind          300
Name: Capacity (MW), dtype: int64


In [192]:
import numpy as np
a = np.array([0, 1, 2, 3]) #Create a rank 1 array
print(a)                   #Print array a 
print(type(a))             #Print type of array a
print(a.ndim)              #Dimension of array a 
print(a.shape)             #Shape(row,column) of array a 
print(len(a))              #Length of array a

[0 1 2 3]
<class 'numpy.ndarray'>
1
(4,)
4


In [194]:
myList = [[1,2,3],[4,5,6],[7,8,9]]
np.array(myList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [200]:
np.random.rand(5) #Uniform distribution of 
np.random.rand(4,4) #Create 2D array of rand
np.random.rand(4) #std. normal distribution

array([0.52358105, 0.42281599, 0.5851907 , 0.35499591])

In [202]:
#Energy consumption in MWh for different renewable sources: Solar, Wind, Hydropower, Geothermal, Biomass
energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

#Print the array
print("Energy Consumption (in MWh) for different renewable sources:")
print(energy_consumption)

Energy Consumption (in MWh) for different renewable sources:
[1200 3400 2900 1800 2500]


In [204]:
#Calculaate the total energy consumption 
total_consumption = np.sum(energy_consumption)
print(f"\n Total energy Consumption: {total_consumption} MWh")


 Total energy Consumption: 11800 MWh


In [214]:
#Calculate the mean energy consumption 
mean_consumption = np.mean(energy_consumption)
print(f"\n Mean energy Consumption: {mean_consumption:.2f} MWh")


 Mean energy Consumption: 2360.00 MWh


In [216]:
#Calculate the standard deviation of energy consumption 
std_deviation = np.std(energy_consumption)
print(f"\nStandard deviation of energy Consumption: {std_deviation:.2f} MWh")


Standard deviation of energy Consumption: 781.28 MWh


In [218]:
#Reshape the array (to 5 rowa and 1 column)
reshaped_array = energy_consumption.reshape((5,1))
print(f"\nReshaped energy Consumption Array: (5x1)")
print(reshaped_array)


Reshaped energy Consumption Array: (5x1)
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]


In [220]:
#Sample data with missing values 
data = {
    "Energy source": ["Solar", "wind", "Hydropower", "Geothermal", "Biomas", "Nuclear"],
    "Energy Consumption (MWh)": [1200, np.nan, 2900, np.nan, 2500, 3200],
    "Cost (Million $)": [200, 400, np.nan, 150, 250, np.nan]
}
#Create a DataFrame 
energy_df = pd.DataFrame(data)

print("Original Energy data with missing values: ")
print(energy_df)

Original Energy data with missing values: 
  Energy source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          wind                       NaN             400.0
2    Hydropower                    2900.0               NaN
3    Geothermal                       NaN             150.0
4        Biomas                    2500.0             250.0
5       Nuclear                    3200.0               NaN


In [222]:
energy_df.isnull().sum()

Energy source               0
Energy Consumption (MWh)    2
Cost (Million $)            2
dtype: int64

In [224]:
energy_df.isnull().sum().sum()

4

In [226]:
#Remove rows with any missing values 
cleaned_df = energy_df.dropna()
print("\nData after removing rows with missing values :")
print(cleaned_df)


Data after removing rows with missing values :
  Energy source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
4        Biomas                    2500.0             250.0


In [228]:
#Impute missing values in 'Energy Consumption (MWh)' with the mean
energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(), inplace=True)

#Impute missing values in 'Cost (Million $)' with the mean
energy_df["Cost (Million $)"].fillna(energy_df["Cost (Million $)"].mean(), inplace=True)

print("\nData After Imputing Missing values with mean:")
print(energy_df)


Data After Imputing Missing values with mean:
  Energy source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4        Biomas                    2500.0             250.0
5       Nuclear                    3200.0             250.0


/var/folders/dh/vkcttlgn1xv6fjp2f1w7kdm80000gn/T/ipykernel_72265/3855679533.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  energy_df["Energy Consumption (MWh)"].fillna(energy_df["Energy Consumption (MWh)"].mean(), inplace=True)
/var/folders/dh/vkcttlgn1xv6fjp2f1w7kdm80000gn/T/ipykernel_72265/3855679533.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the

In [232]:
#Forward fill missing values 
forward_filled_df = energy_df.fillna(method="ffill")
print("\nData after forward filling: ")
print(forward_filled_df)


Data after forward filling: 
  Energy source  Energy Consumption (MWh)  Cost (Million $)
0         Solar                    1200.0             200.0
1          wind                    2450.0             400.0
2    Hydropower                    2900.0             250.0
3    Geothermal                    2450.0             150.0
4        Biomas                    2500.0             250.0
5       Nuclear                    3200.0             250.0


/var/folders/dh/vkcttlgn1xv6fjp2f1w7kdm80000gn/T/ipykernel_72265/1480210650.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_filled_df = energy_df.fillna(method="ffill")


In [246]:
#create a flag column indicating missing values in 'Energy consumption (MWh)'
energy_df["Missing Consumption"] = energy_df["Energy Consumption (MWh)"].isna().astype(int)
print("\nData With Missing Values Flagged:")
print(energy_df)


Data With Missing Values Flagged:
  Energy source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                    1200.0             200.0   
1          wind                    2450.0             400.0   
2    Hydropower                    2900.0             250.0   
3    Geothermal                    2450.0             150.0   
4        Biomas                    2500.0             250.0   
5       Nuclear                    3200.0             250.0   

   Missing Consumption  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    0  


In [250]:
from sklearn.preprocessing import MinMaxScaler

#Normalize the 'Energy Consumption (MWh)' and 'Cost (Million $)'
scaler = MinMaxScaler()
energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] = scaler.fit_transform(
    energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]]
)

print("\nData after normalization (Min-Max Scaling):")
print(energy_df)


Data after normalization (Min-Max Scaling):
  Energy source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar                     0.000               0.2   
1          wind                     0.625               1.0   
2    Hydropower                     0.850               0.4   
3    Geothermal                     0.625               0.0   
4        Biomas                     0.650               0.4   
5       Nuclear                     1.000               0.4   

   Missing Consumption  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    0  


In [254]:
from sklearn.preprocessing import StandardScaler

# Standardize the 'Energy Consumption (MWh)' and 'Cost (Million $)'

scaler = StandardScaler()

energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] = scaler.fit_transform(

energy_df[["Energy Consumption (MWh)", "Cost (Million $)"]] )

print("\nData After Standardization (Z-score Scaling):")

print(energy_df)


Data After Standardization (Z-score Scaling):
  Energy source  Energy Consumption (MWh)  Cost (Million $)  \
0         Solar             -2.005893e+00     -6.546537e-01   
1          wind              3.563181e-16      1.963961e+00   
2    Hydropower              7.221213e-01      1.817029e-16   
3    Geothermal              3.563181e-16     -1.309307e+00   
4        Biomas              8.023570e-02      1.817029e-16   
5       Nuclear              1.203536e+00      1.817029e-16   

   Missing Consumption  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
5                    0  


In [284]:
#One-hot encode the 'Energy Source' column
energy_encoded_df = pd.get_dummies(energy_df, columns=["Energy Source"])
print("\nData after one-hot encoding categorical variables:")
print(energy_encoded_df)

KeyError: "None of [Index(['Energy Source'], dtype='object')] are in the [columns]"

In [282]:
#Create a new feature: Energy Consumption per Million $
energy_encoded_df["Consumption per $Million"] = energy_encoded_df["Energy Consumption (MWh)"] / energy_encoded_df["Cost (Million $)"]

print("\nData with new feature(consumption per $million):")
print(energy_encoded_df)

NameError: name 'energy_encoded_df' is not defined